name: Deploy Multi-Region EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # 👈 necesario para OIDC
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::351247743848:oidc-provider/token.actions.githubusercontent.com   # 👈 ARN del rol que creaste
          aws-region: us-east-1

      - name: Debug identity
        run: aws sts get-caller-identity

      - name: Debug AWS Identity
        run: aws sts get-caller-identity

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Update kubeconfig for primary
        run: aws eks --region $PRIMARY_REGION update-kubeconfig --name $CLUSTER_PRIMARY

      - name: Deploy nginx to primary
        run: kubectl apply -f terraform/nginx-deployment.yaml

      - name: Verify nginx in primary
        run: kubectl get pods -n default -o wide

      - name: Update kubeconfig for secondary
        run: aws eks --region $SECONDARY_REGION update-kubeconfig --name $CLUSTER_SECONDARY

      - name: Deploy nginx to secondary
        run: kubectl apply -f terraform/nginx-deployment.yaml

      - name: Verify nginx in secondary
        run: kubectl get pods -n default -o wide

      - name: Verify nginx in secondary
        run: kubectl get pods -n default -o wide
